comment = "#6d7f8b"

background = [
  "#0f1c1e", # bg0
  "#152528", # bg1
  "#1d3337", # bg2
  "#254147", # bg3
  "#2d4f56"  # bg4
]

foreground = [
  "#eaeeee", # fg0
  "#e6eaea", # fg1
  "#cbd9d8", # fg2
  "#587b7b"  # fg3
]

selection = [
  "#293e40", # sel0
  "#425e5e"  # sel1
]

[base]
black   = "#2F3239"
red     = "#e85c51"
green   = "#7aa4a1"
yellow  = "#fda47f"
blue    = "#5a93aa"
magenta = "#ad5c7c"
cyan    = "#a1cdd8"
white   = "#ebebeb"
orange  = "#ff8349"
pink    = "#cb7985"

[bright]
black   = "#4e5157"
red     = "#eb746b"
green   = "#8eb2af"
yellow  = "#fdb292"
blue    = "#73a3b7"
magenta = "#b97490"
cyan    = "#afd4de"
white   = "#eeeeee"
orange  = "#ff9664"
pink    = "#d38d97"

[dim]
black   = "#282a30"
red     = "#c54e45"
green   = "#688b89"
yellow  = "#d78b6c"
blue    = "#4d7d90"
magenta = "#934e69"
cyan    = "#89aeb8"
white   = "#c8c8c8"
orange  = "#d96f3e"
pink    = "#ad6771"

[diff]
add    = "#263a3c"
delete = "#3f3030"
change = "#2c4145"
text   = "#395156"
